### ISSUE TITLE
[DSPL]HSRの仕様について

### ISSUE THREAD

**Issue by YutaroISHIDA** [RoboCupAtHomeJP/Rule2018#1]
九工大 石田です．
このルールはRoboCup@Home 2017/2018のルールに基づいて決定されていると推測し，ご質問いたします．

2018年の世界大会では，DSPLでOfficial Standard Laptopの使用が許可されていますが，ジャパンオープンでも許可されますでしょうか？
世界大会の練習も兼ねて使用したい，と考えています．

**Comment by RoboCupAtHomeJP** [comment]
返信おそくなり申し訳ありません．
2018年のルールブックに記載されているOfficial Standard Laptopは使用可能となります．
