### ISSUE TITLE
[DSPL] Official microphoneについて

### ISSUE THREAD

**Issue by YutaroISHIDA** [RoboCupAtHomeJP/Rule2018#3]
[DSPL] Official microphoneはないため，各チームが独自で準備したBluetoothマイクを利用することができる．  
  
ということですが，  マイクの接続先は
・External computer（RoboCup 2017 Nagoyaで採用された方式）  
・HSRまたはOfficial Standard Laptop  
どちらも許可されますでしょうか？

**Comment by RoboCupAtHomeJP** [comment]
はい，接続先はどちらでも構いません．External computerを使用する場合には，通信するためのネットワークをチームが独自で用意する必要があります．
