### ISSUE TITLE
[DSPL] 独自に用意するWiFiについて

### ISSUE THREAD

**Issue by YutaroISHIDA** [RoboCupAtHomeJP/Rule2018#5]
@HoriThe3rd お腹空きました．

DSPLにおける，WiFiの取り扱いについて質問がございます．

WiFiの混雑を避けるために，モバイルWiFiルータ・クレードルを
HSRの上に直接搭載することは許可出来ますか？
例: http://www.aterm.jp/product/atermstation/product/mobile/mr05ln/

まだ技術的に可能か実証していませんが，
以下のような構成でセルラー回線のみ使用すれば，
WiFiの混雑は多少緩和されるのではないかと考えております．

①モバイルWiFiルータ・クレードル
②HSR
③Official Standard Laptop

A NIC付きEth-USB変換
B HSRアクセスパネルLANポート

① --[A]-- ② --[B]-- ③

**Comment by naka-tomo** [comment]
モバイルwifi，クレードル，小型のLANハブの使用を許可することとなりました．
ただし，クレードルはHSRの肩にのせ，LANケーブル等は目立たないように配線することが条件となります．

**Comment by YutaroISHIDA** [comment]
ありがとうございます．

■データ通信
HSR
　　-- 小型LANハブ
　　　　-- Alienware
　　　　-- クレードル・モバイルWiFiルータ

■給電
Alienware
　　-- USBハブ（給電用USBケーブルを分岐させるため）
　　　　-- 小型LANハブ
　　　　-- クレードル・モバイルWiFiルータ

我々は上記の構成で運用する予定です．
